version: 2

build:
  image: testing

sphinx:
  configuration: midocu/conf.py

python:
  version: "3.9"
  install:
   - method: pip
     path: midocu
   - requirements: midocu/docs/requirements.txt
      cjarla-
